openapi: 3.0.1
info:
  title: Microservice-Template
  description: This is a sample documentation for the Unline Microservice-Template
  termsOfService: ""
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
servers:
- url: https://localhost:8080/v1
- url: http://localhost:8080/v1
tags:
- name: version
  description: Will show debug info
paths:
  /version:
    post:
      tags:
      - version
      summary: Get debug info
      description: This will return JSON of service name, Port, version
      operationId: getVersion
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponse'
        500:
          description: Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponse'
components:
  schemas:
    ApiResponse:
      type: object
      properties:
        code:
          type: integer
          format: int32
        type:
          type: string
        message:
          type: object
          properties: {}
