swagger: "2.0"
info:
  description: "This is a sample documentation for the Unline Microservice-Template"
  version: "1.0.0"
  title: "Microservice-Template"
  termsOfService: ""
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "localhost:8080"
basePath: "/v1"
tags:
- name: "version"
  description: "Will show debug info"
schemes:
- "https"
- "http"
paths:
  /version:
    post:
      tags:
      - "version"
      summary: "Get debug info"
      description: "This will return JSON of service name, Port, version"
      operationId: "getVersion"
      produces:
      - "application/json"
      responses:
        "500":
          description: "Server Error"
          schema:
            $ref: "#/definitions/ApiResponse"
        "200":
          description: "successful operation"
          schema:
            $ref: "#/definitions/ApiResponse"
definitions:
  ApiResponse:
      type: "object"
      properties:
        code:
          type: "integer"
          format: "int32"
        type:
          type: "string"
        message:
          type: "object"